# task 2

这一部分的目标是按组员分别处理各自选定的 SA4 区域。先用 NSW Administrative Boundaries API 找到每个 SA4 中被包含的 SA2，再用 NSW POI API 找到这些 SA2 的 bbox 中所有的 POI，最后把结果保存到本地 sqlite 数据库。

In [28]:
import pandas as pd
from pathlib import Path
import requests

# get relative path
current_dir = Path.cwd()
data_path = current_dir / "data" / "Region summary_ New South Wales STE 1.csv"

try:
    df = pd.read_csv(data_path)
    print(f"{data_path} successfully loaded")
except:
    print(f"cannot find target {data_path}")


/Users/felix/projects/group_DATA2001/data/Region summary_ New South Wales STE 1.csv successfully loaded


## selected sa4 codes

Selected SA4 codes are：120、117、118、125


In [29]:
import importlib
from IPython.display import display
import task2_sa2

importlib.reload(task2_sa2)

available_sa4s = task2_sa2.list_nsw_sa4s()

member_zone_df = pd.DataFrame(
    {
        "member_name": ["member_1", "member_2", "member_3", "member_4"],
        "sa4_code": ["120", "117", "118", "125"],
    }
)

member_zone_df = member_zone_df.merge(
    available_sa4s.rename(columns={"SA4_CODE": "sa4_code", "SA4_NAME": "sa4_name"}),
    on="sa4_code",
    how="left",
)

display(member_zone_df)


,member_name,sa4_code,sa4_name
0,member_1,120,Sydney - Inner West
1,member_2,117,Sydney - City and Inner South
2,member_3,118,Sydney - Eastern Suburbs
3,member_4,125,Sydney - Parramatta


### Area 1

Leo selected `SA4_CODE = 120`, which is  `Sydney - Inner West`. First to look up all the including SA2 area within the SA4, and then find every POI in the given SA2 bounding box.

In [30]:
member_1_sa2_bbox_df = task2_sa2.get_sa2_bbox_df_by_code("120")
member_1_sa2_bbox_df["member_name"] = "member_1"
display(member_1_sa2_bbox_df[["member_name", "sa4_code", "sa4_name", "sa2_main", "sa2_name"]])

member_1_poi_df = task2_sa2.get_sa4_poi_df_by_code("120")
member_1_poi_df["member_name"] = "member_1"
display(member_1_poi_df.head())

member_1_poi_count_df = member_1_poi_df.groupby("sa2_name").size().reset_index(name="poi_count")
display(member_1_poi_count_df)


,member_name,sa4_code,sa4_name,sa2_main,sa2_name
0,member_1,120,Sydney - Inner West,120011384,Concord West - North Strathfield
1,member_1,120,Sydney - Inner West,120021387,Balmain
2,member_1,120,Sydney - Inner West,120031390,Ashfield
3,member_1,120,Sydney - Inner West,120031393,Croydon Park - Enfield
4,member_1,120,Sydney - Inner West,120031396,Homebush
5,member_1,120,Sydney - Inner West,120031391,Burwood - Croydon
6,member_1,120,Sydney - Inner West,120011385,Drummoyne - Rodd Point
7,member_1,120,Sydney - Inner West,120031397,Strathfield
8,member_1,120,Sydney - Inner West,120021388,Leichhardt - Annandale
9,member_1,120,Sydney - Inner West,120031394,Dulwich Hill - Lewisham


,objectid,poiname,poitype,poigroup,longitude,latitude,sa4_code,sa4_name,sa2_main,sa2_name,member_name
0,848,CONCORD WEST POST OFFICE,Post Office,1,151.086920,-33.848207,120,Sydney - Inner West,120011384,Concord West - North Strathfield,member_1
1,852,None,Place Of Worship,1,151.100483,-33.861704,120,Sydney - Inner West,120011384,Concord West - North Strathfield,member_1
2,916,TREILLAGE TOWER,Observation Tower,3,151.079081,-33.847984,120,Sydney - Inner West,120011384,Concord West - North Strathfield,member_1
3,1120,CONCORD GOLF COURSE,Golf Course,3,151.097332,-33.850397,120,Sydney - Inner West,120011384,Concord West - North Strathfield,member_1
4,1128,HENLEY PARK,Park,3,151.098725,-33.859951,120,Sydney - Inner West,120011384,Concord West - North Strathfield,member_1


,sa2_name,poi_count
0,Ashfield,193
1,Balmain,283
2,Burwood - Croydon,187
3,Canterbury (North) - Ashbury,72
4,Concord - Mortlake - Cabarita,294
5,Concord West - North Strathfield,166
6,Croydon Park - Enfield,92
7,Drummoyne - Rodd Point,435
8,Dulwich Hill - Lewisham,117
9,Five Dock - Abbotsford,193


### Area 2

Lanfei Yan is responsible to `SA4_CODE = 117`, which is `Sydney - City and Inner South`. This is logically identical as before, SA2 first and then POI within the SA2 bouding box.

In [31]:
member_2_sa2_bbox_df = task2_sa2.get_sa2_bbox_df_by_code("117")
member_2_sa2_bbox_df["member_name"] = "member_2"
display(member_2_sa2_bbox_df[["member_name", "sa4_code", "sa4_name", "sa2_main", "sa2_name"]])

member_2_poi_df = task2_sa2.get_sa4_poi_df_by_code("117")
member_2_poi_df["member_name"] = "member_2"
display(member_2_poi_df.head())

member_2_poi_count_df = member_2_poi_df.groupby("sa2_name").size().reset_index(name="poi_count")
display(member_2_poi_count_df)


,member_name,sa4_code,sa4_name,sa2_main,sa2_name
0,member_2,117,Sydney - City and Inner South,117011324,Port Botany Industrial
1,member_2,117,Sydney - City and Inner South,117031338,Waterloo - Beaconsfield
2,member_2,117,Sydney - City and Inner South,117031335,Redfern - Chippendale
3,member_2,117,Sydney - City and Inner South,117021327,Petersham - Stanmore
4,member_2,117,Sydney - City and Inner South,117011321,Botany
5,member_2,117,Sydney - City and Inner South,117031330,Erskineville - Alexandria
6,member_2,117,Sydney - City and Inner South,117031336,Surry Hills
7,member_2,117,Sydney - City and Inner South,117011322,Mascot - Eastlakes
8,member_2,117,Sydney - City and Inner South,117031333,Potts Point - Woolloomooloo
9,member_2,117,Sydney - City and Inner South,117031334,Pyrmont - Ultimo


,objectid,poiname,poitype,poigroup,longitude,latitude,sa4_code,sa4_name,sa2_main,sa2_name,member_name
0,2791,FRED WILLIAMS RESERVE,Park,3,151.235054,-33.980692,117,Sydney - City and Inner South,117011324,Port Botany Industrial,member_2
1,3009,BOTANY MUNICIPAL GOLF LINKS,Golf Course,3,151.209774,-33.960649,117,Sydney - City and Inner South,117011324,Port Botany Industrial,member_2
2,3011,BICENTENNIAL PARK,Park,3,151.229946,-33.979046,117,Sydney - City and Inner South,117011324,Port Botany Industrial,member_2
3,3013,BOTANY CEMETERY,Cemetery,1,151.228252,-33.973462,117,Sydney - City and Inner South,117011324,Port Botany Industrial,member_2
4,3044,PRAISE EVANGELICAL FREE CHURCH OF AUSTRALIA,Place Of Worship,1,151.232717,-33.959938,117,Sydney - City and Inner South,117011324,Port Botany Industrial,member_2


,sa2_name,poi_count
0,Banksmeadow,23
1,Botany,45
2,Darlinghurst,92
3,Erskineville - Alexandria,95
4,Glebe - Forest Lodge,117
5,Marrickville,394
6,Mascot - Eastlakes,104
7,Newtown - Camperdown - Darlington,240
8,Pagewood - Hillsdale - Daceyville,113
9,Petersham - Stanmore,108


### Area 3

Qianxue Yu has selected `SA4_CODE = 118`，which is `Sydney - Eastern Suburbs`. Same as before.

In [32]:
member_3_sa2_bbox_df = task2_sa2.get_sa2_bbox_df_by_code("118")
member_3_sa2_bbox_df["member_name"] = "member_3"
display(member_3_sa2_bbox_df[["member_name", "sa4_code", "sa4_name", "sa2_main", "sa2_name"]])

member_3_poi_df = task2_sa2.get_sa4_poi_df_by_code("118")
member_3_poi_df["member_name"] = "member_3"
display(member_3_poi_df.head())

member_3_poi_count_df = member_3_poi_df.groupby("sa2_name").size().reset_index(name="poi_count")
display(member_3_poi_count_df)


,member_name,sa4_code,sa4_name,sa2_main,sa2_name
0,member_3,118,Sydney - Eastern Suburbs,118011344,Dover Heights
1,member_3,118,Sydney - Eastern Suburbs,118011341,Bondi Junction - Waverly
2,member_3,118,Sydney - Eastern Suburbs,118011347,Woollahra
3,member_3,118,Sydney - Eastern Suburbs,118021350,Malabar - La Perouse - Chifley
4,member_3,118,Sydney - Eastern Suburbs,118011342,Centennial Park
5,member_3,118,Sydney - Eastern Suburbs,118011339,Bondi - Tamarama - Bronte
6,member_3,118,Sydney - Eastern Suburbs,118021348,Coogee - Clovelly
7,member_3,118,Sydney - Eastern Suburbs,118021351,Maroubra
8,member_3,118,Sydney - Eastern Suburbs,118011345,Paddington - Moore Park
9,member_3,118,Sydney - Eastern Suburbs,118021352,Randwick


,objectid,poiname,poitype,poigroup,longitude,latitude,sa4_code,sa4_name,sa2_main,sa2_name,member_name
0,2299,RALEIGH RESERVE,Park,3,151.282547,-33.876566,118,Sydney - Eastern Suburbs,118011344,Dover Heights,member_3
1,2412,None,Park,3,151.283756,-33.868246,118,Sydney - Eastern Suburbs,118011344,Dover Heights,member_3
2,2424,DUMARESQ RESERVE,Park,3,151.270533,-33.866232,118,Sydney - Eastern Suburbs,118011344,Dover Heights,member_3
3,2473,ST ANDREW'S PRESBYTERIAN CHURCH,Place Of Worship,1,151.271366,-33.870861,118,Sydney - Eastern Suburbs,118011344,Dover Heights,member_3
4,2474,CAFFYN PARK,Park,3,151.278907,-33.872666,118,Sydney - Eastern Suburbs,118011344,Dover Heights,member_3


,sa2_name,poi_count
0,Bondi - Tamarama - Bronte,80
1,Bondi Beach - North Bondi,77
2,Bondi Junction - Waverly,104
3,Centennial Park,59
4,Coogee - Clovelly,126
5,Double Bay - Bellevue Hill,286
6,Dover Heights,55
7,Kensington - Kingsford,134
8,Malabar - La Perouse - Chifley,226
9,Maroubra,155


### Area 4

Qingyi Zhu selected `SA4_CODE = 125`, which is `Sydney - Parramatta`.

In [33]:
member_4_sa2_bbox_df = task2_sa2.get_sa2_bbox_df_by_code("125")
member_4_sa2_bbox_df["member_name"] = "member_4"
display(member_4_sa2_bbox_df[["member_name", "sa4_code", "sa4_name", "sa2_main", "sa2_name"]])

member_4_poi_df = task2_sa2.get_sa4_poi_df_by_code("125")
member_4_poi_df["member_name"] = "member_4"
display(member_4_poi_df.head())

member_4_poi_count_df = member_4_poi_df.groupby("sa2_name").size().reset_index(name="poi_count")
display(member_4_poi_count_df)


,member_name,sa4_code,sa4_name,sa2_main,sa2_name
0,member_4,125,Sydney - Parramatta,125031487,Yennora Industrial
1,member_4,125,Sydney - Parramatta,125031481,Granville - Clyde
2,member_4,125,Sydney - Parramatta,125041493,Toongabbie - Constitution Hill
3,member_4,125,Sydney - Parramatta,125011473,Homebush Bay - Silverwater
4,member_4,125,Sydney - Parramatta,125031484,Guildford West - Merrylands West
5,member_4,125,Sydney - Parramatta,125041490,North Rocks
6,member_4,125,Sydney - Parramatta,125021476,Carlingford
7,member_4,125,Sydney - Parramatta,125031485,Merrylands - Holroyd
8,member_4,125,Sydney - Parramatta,125031479,Chester Hill - Sefton
9,member_4,125,Sydney - Parramatta,125041488,Girraween - Westmead


,objectid,poiname,poitype,poigroup,longitude,latitude,sa4_code,sa4_name,sa2_main,sa2_name,member_name
0,1960,LINNWOOD MUSEUM,Museum,1,150.976257,-33.854700,125,Sydney - Parramatta,125031487,Yennora Industrial,member_4
1,1961,CARRINGTON ROAD PARK,Park,3,150.979534,-33.858424,125,Sydney - Parramatta,125031487,Yennora Industrial,member_4
2,2038,MCCREDIE PARK,Park,3,150.972060,-33.854984,125,Sydney - Parramatta,125031487,Yennora Industrial,member_4
3,2252,None,Place Of Worship,1,150.979047,-33.856015,125,Sydney - Parramatta,125031487,Yennora Industrial,member_4
4,2253,None,Place Of Worship,1,150.980362,-33.854497,125,Sydney - Parramatta,125031487,Yennora Industrial,member_4


,sa2_name,poi_count
0,Auburn,210
1,Carlingford,177
2,Chester Hill - Sefton,151
3,Ermington - Rydalmere,170
4,Fairfield - East,132
5,Girraween - Westmead,308
6,Granville - Clyde,186
7,Greystanes - Pemulwuy,156
8,Guildford - South Granville,144
9,Guildford West - Merrylands West,179


### Combine and Save

The results from the four group members above were run separately. Finally, the SA2 and POI tables from all four individuals were merged and saved to a local SQLite database. The `poi` and `sa2_bbox` tables were then joined within the database using `sa2_main`.

In [34]:
all_sa2_bbox_df = pd.concat(
    [
        member_1_sa2_bbox_df,
        member_2_sa2_bbox_df,
        member_3_sa2_bbox_df,
        member_4_sa2_bbox_df,
    ],
    ignore_index=True,
)

all_poi_df = pd.concat(
    [
        member_1_poi_df,
        member_2_poi_df,
        member_3_poi_df,
        member_4_poi_df,
    ],
    ignore_index=True,
)

all_sa2_bbox_df = all_sa2_bbox_df[
    [
        "member_name",
        "sa4_code",
        "sa4_name",
        "sa2_main",
        "sa2_name",
        "state_name",
        "area_sqkm",
        "bbox_xmin",
        "bbox_ymin",
        "bbox_xmax",
        "bbox_ymax",
    ]
]

all_poi_df = all_poi_df[
    [
        "objectid",
        "poiname",
        "poitype",
        "poigroup",
        "longitude",
        "latitude",
        "member_name",
        "sa4_code",
        "sa4_name",
        "sa2_main",
        "sa2_name",
    ]
]

db_path = current_dir / "data" / "task2_poi.db"
task2_sa2.save_to_sqlite(all_sa2_bbox_df, all_poi_df, str(db_path))
print(db_path)

schema_df = task2_sa2.read_sql(
    "select name, sql from sqlite_master where type = 'table' order by name",
    str(db_path),
)
display(schema_df)

join_df = task2_sa2.read_sql(
    "select p.poi_id, p.member_name, p.poiname, p.poitype, s.sa4_code, s.sa4_name, s.sa2_name from poi p join sa2_bbox s on p.sa2_main = s.sa2_main limit 20",
    str(db_path),
)
display(join_df)


/Users/felix/projects/group_DATA2001/data/task2_poi.db


,name,sql
0,poi,CREATE TABLE poi (\n poi_id integer...
1,sa2_bbox,CREATE TABLE sa2_bbox (\n member_na...
2,sqlite_sequence,"CREATE TABLE sqlite_sequence(name,seq)"


,poi_id,member_name,poiname,poitype,sa4_code,sa4_name,sa2_name
0,1,member_1,CONCORD WEST POST OFFICE,Post Office,120,Sydney - Inner West,Concord West - North Strathfield
1,2,member_1,None,Place Of Worship,120,Sydney - Inner West,Concord West - North Strathfield
2,3,member_1,TREILLAGE TOWER,Observation Tower,120,Sydney - Inner West,Concord West - North Strathfield
3,4,member_1,CONCORD GOLF COURSE,Golf Course,120,Sydney - Inner West,Concord West - North Strathfield
4,5,member_1,HENLEY PARK,Park,120,Sydney - Inner West,Concord West - North Strathfield
5,6,member_1,CENTRAL PARK,Park,120,Sydney - Inner West,Concord West - North Strathfield
6,7,member_1,WARBRICK PARK,Park,120,Sydney - Inner West,Concord West - North Strathfield
7,8,member_1,MUTTON RESERVE,Park,120,Sydney - Inner West,Concord West - North Strathfield
8,9,member_1,WALKER RESERVE,Park,120,Sydney - Inner West,Concord West - North Strathfield
9,10,member_1,BENNELONG PARK,Park,120,Sydney - Inner West,Concord West - North Strathfield
